Repository Team-YUMU/YUMU-FE, pull requests merged in 2024-04, with the labels that each got.

#171 마이페이지 내역화면 기능구현
  .vscode/settings.json
  package-lock.json
  package.json
  public/svgs/buy-history-null-icon.svg
  public/svgs/sales-history-null-icon.svg
  public/svgs/wish-history-null-icon.svg
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/pages/_app.tsx
  src/services/api.ts
Labels: :bug: Bug Fix, :bulb: Feature, :gear: Setting

#172 Footer UI 적용
  public/svgs/M.svg
  public/svgs/U.svg
  public/svgs/Y.svg
  src/components/common/Footer.tsx
  tailwind.config.ts
Labels: :bulb: Feature

#174 Signin 페이지 이메일중복확인기능 구혀
  src/pages/signin/callback/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/services/api.ts
  src/types/validator/signForm.ts
Labels: :bug: Bug Fix, 🔩 chore

#180 feat: 검색 페이지 API 연동
  public/images/heart.png
  public/svgs/empty_view.svg
  src/components/common/AuctionCard.tsx
  src/components/common/BestAuction.tsx
  src/components/common/EmptyView.tsx
  src/components/common/Pagination.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SortSelect.tsx
  src/components/domain/landing/LandingLivePopular.tsx
  src/components/domain/search/AuctionList.tsx
  src/mocks/Auction.ts
  src/pages/landing/index.tsx
  src/pages/search/index.tsx
  src/services/api.ts
  src/types/types.ts
Labels: :art: Style, :bulb: Feature

#181 feat: 상세 페이지 API 연동
  src/components/common/LiveTimer.tsx
  src/mocks/auctionDetail.json
  src/pages/auction/[auctionid]/detail/index.tsx
Labels: :bulb: Feature, 🖼️Design

#182 경매 등록 & 경매 상세 자잘한 수정
  src/components/common/AuctionDetail.tsx
  src/components/common/InfoBox.tsx
  src/components/domain/live/livevideo.tsx
  src/mocks/Art.ts
  src/mocks/Auction.ts
  src/mocks/Member.ts
  src/mocks/PurchaseHistory.ts
  src/mocks/SalesHistory.ts
  src/mocks/WishList.ts
  src/mocks/auctionDetail.json
  src/mocks/testArts.json
  src/pages/auction/[auctionid]/detail/index.tsx
  src/pages/auction/[auctionid]/live/index.tsx
  src/pages/auction/[auctionid]/streaming/index.tsx
  src/pages/registration/index.tsx
  src/types/types.ts
Labels: :bulb: Feature

#185 Signup 페이지 이메일, 닉네임 중복체크 검사
  src/pages/signup/index.tsx
Labels: :bulb: Feature, 🔩 chore

#189 더보기 svg / carousel 버튼 / header 수정
  src/components/common/Header.tsx
  src/components/domain/landing/LadingPopular.tsx
  src/components/domain/landing/LandingLivePopular.tsx
  src/components/svgs/ColorChangeMoreArrow.tsx
  src/components/ui/button.tsx
  src/components/ui/mainCarousel.tsx
  src/pages/landing/index.tsx
Labels: :bulb: Feature, 🖼️Design

#192 Revert "메인 2차 머지"
  public/images/heart.png
  public/images/payment_icon_yellow.png
  public/svgs/empty_view.svg
  src/components/common/AuctionCard.tsx
  src/components/common/AuctionDetail.tsx
  src/components/common/BestAuction.tsx
  src/components/common/EmptyView.tsx
  src/components/common/Header.tsx
  src/components/common/InfoBox.tsx
  src/components/common/LiveTimer.tsx
  src/components/common/Pagination.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SortSelect.tsx
  src/components/domain/landing/LadingPopular.tsx
  src/components/domain/landing/LandingLivePopular.tsx
  src/components/domain/live/livevideo.tsx
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/Edit/NewPasswordModalForm.tsx
  src/components/domain/myPage/Tabs/MyPageTabs.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/components/domain/search/AuctionList.tsx
  src/components/svgs/ColorChangeMoreArrow.tsx
  src/components/ui/button.tsx
  src/components/ui/mainCarousel.tsx
  src/mocks/Art.ts
  src/mocks/Auction.ts
  src/mocks/Member.ts
  src/mocks/PurchaseHistory.ts
  src/mocks/SalesHistory.ts
  src/mocks/WishList.ts
  src/mocks/testArts.json
  src/pages/auction/[auctionid]/detail/index.tsx
  src/pages/auction/[auctionid]/live/index.tsx
  src/pages/auction/[auctionid]/streaming/index.tsx
  src/pages/landing/index.tsx
  src/pages/registration/index.tsx
  src/pages/search/index.tsx
  src/pages/signup/index.tsx
  src/services/api.ts
  src/types/types.ts
Labels: 🔩 chore

#197 수정 컴포넌트 쿼리 적용 및 목록 클릭시 해당 상세페이지로 이동 구현
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/Edit/IntroEditForm.tsx
  src/components/domain/myPage/Tabs/Edit/NewPasswordModalForm.tsx
  src/components/domain/myPage/Tabs/Edit/NickNameEditForm.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/pages/mypage/index.tsx
  tailwind.config.ts
Labels: :bug: Bug Fix, :bulb: Feature, 🔩 chore

#199 경매 등록 UI 일부 수정
  src/components/common/InfoBox.tsx
  src/pages/registration/index.tsx
Labels: :bulb: Feature, 🖼️Design

#201 경매 등록 페이지 Textarea scrollbar-hide 및 잘못된 최대 입력자 제한 해제
  src/pages/registration/index.tsx
Labels: 🖼️Design

#206 상세 페이지 디자인 디테일 수정 및 데이터 바인딩 수정
  src/components/common/AuctionCard.tsx
  src/components/common/AuctionDetailHeader.tsx
  src/pages/auction/[auctionid]/detail/index.tsx
  src/pages/landing/index.tsx
Labels: :hammer_and_wrench: Refactor, 🖼️Design

#209 헤더 컴포넌트 MemberInfo api query 적용
  .vscode/settings.json
  package-lock.json
  package.json
  public/fonts/.gitkeep
  src/components/common/Header.tsx
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/domain/myPage/Tabs/Edit/NickNameEditForm.tsx
  src/lib/Date.ts
  src/pages/_app.tsx
  src/states/.gitkeep
  src/utils/.gitkeep
Labels: :hammer_and_wrench: Refactor

#211 ws 모듈을 활용하여 stomp 재시도
  package-lock.json
  package.json
  src/pages/chatting/[roomId].tsx
  src/pages/chatting/index.tsx
  src/services/api.ts
  src/services/stomp.ts
  src/services/ws.ts
  src/types/next.ts
Labels: :bulb: Feature

#214 마이페이지 리팩토링
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/Edit/IntroEditForm.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/services/api.ts
Labels: :hammer_and_wrench: Refactor

#216 경매 등록 페이지 Textarea scrollbar-hide 및 잘못된 최대 입력자 제한 해제
  src/pages/auction/[auctionid]/detail/index.tsx
Labels: :bug: Bug Fix, 🖼️Design

#218 로그인/회원가입 페이지 헤더 설정
  src/components/common/Header.tsx
  src/pages/_app.tsx
Labels: :hammer_and_wrench: Refactor

#220 로그인 페이지 사용자 정보 없음(404) 모달 작성
  src/pages/signin/index.tsx
  src/services/api.ts
Labels: :bulb: Feature, 🔩 chore

#226 소켓 연결부터 구독 및 채팅까지 live 페이지에 적용
  src/components/domain/live/BidHistories.tsx
  src/components/domain/live/chats.tsx
  src/components/domain/live/livechatting.tsx
  src/pages/chatting/[roomId].tsx
Labels: :bulb: Feature

#232 마이페이지, 로그인/회원가입 페이지 스타일 수정
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: :art: Style

#234 채팅 누적 실패 버그 해결
  src/components/domain/live/livechatting.tsx
Labels: :hammer_and_wrench: Refactor

#235 feat: 404 에러 페이지 구현
  public/images/not_found.png
  src/pages/404.tsx
Labels: :bulb: Feature

#236 회원가입 인풋 에러메시지 겹치는 문제 해결
  src/pages/signup/index.tsx
Labels: :bug: Bug Fix

#237 실시간 채팅에 본인 닉네임을 memberId로 전달하는 기능 추가
  src/components/domain/live/chats.tsx
  src/components/domain/live/livechatting.tsx
Labels: :bulb: Feature

#239 랜딩페이지 환경 변수 추가
  src/components/domain/landing/LandingBanner.tsx
  src/pages/landing/index.tsx
Labels: 🔩 chore

#242 현재 입찰가 웹소켓 연결(기획 변경됨)
  src/components/domain/live/BidHistories.tsx
  src/components/domain/live/CurrentBidBox.tsx
  src/pages/auction/[auctionid]/live/index.tsx
Labels: :bulb: Feature

#244 찜 목록 Query Key 값 수정 및 하트 버튼 호버시 빈 하트 되게 수정
  src/components/domain/myPage/Tabs/WishList.tsx
Labels: :bug: Bug Fix

#250 회원가입 완료가 안되는 문제 해결
  src/pages/signup/index.tsx
Labels: :bug: Bug Fix

#259 마이페이지 리팩토링
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/domain/myPage/Tabs/Edit/NewPasswordModalForm.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/components/ui/spinner.tsx
  src/pages/mypage/index.tsx
Labels: :art: Style, :bulb: Feature, :hammer_and_wrench: Refactor

#268 net::ERR_SSL_PROTOCOL_ERROR 에러 해결
  next.config.mjs
  package.json
  src/pages/_app.tsx
  src/services/axios.ts
Labels: :bug: Bug Fix

#275 토큰 관리 수정
  src/services/api.ts
  src/services/axios.ts
Labels: :hammer_and_wrench: Refactor

#277 refactor : Header/Mypage useQuery,infiniteQuery staleTime 설정
  src/components/common/Header.tsx
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
Labels: :hammer_and_wrench: Refactor
