Repository Team-YUMU/YUMU-FE, pull requests merged in 2024-03, with the labels that each got.

#5 Mockup 데이터 구축
  .eslintrc.json
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/버그-리포트.md
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  postcss.config.js
  src/mocks/Auction.ts
  src/mocks/Member.ts
  src/mocks/PurchaseHistory.ts
  src/mocks/SalesHistory.ts
  src/mocks/WishList.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/auctionlist/[auctionid]/index.tsx
  src/pages/auctionlist/[auctionid]/live/index.tsx
  src/pages/auctionlist/index.tsx
  src/pages/index.tsx
  src/pages/landing/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  src/types/types.ts
  tailwind.config.ts
Labels: 📄 Documentation, :bulb: Feature

#9 Shadcn/ui 설치 및 세팅
  components.json
  package-lock.json
  package.json
  src/components/Button/.gitkeep
  src/components/Input/.gitkeep
  src/components/modal/.gitkeep
  src/lib/utils.ts
  src/libs/.gitkeep
  src/styles/globals.css
  tailwind.config.ts
Labels: :gear: Setting

#14 design : tailwind.config/globals.css 수정
  pull_request_template.md
  src/components/ui/input.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🖼️Design

#22 공통 Layout 컴포넌트 추가 및 시멘틱 태그 수정
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: :bulb: Feature

#20 Live 경매(구매자) 페이지 와이어 프레임 작성
  package-lock.json
  package.json
  src/components/common/AuctionDetailContents.tsx
  src/components/common/ExhibitionCarousel.tsx
  src/components/domain/live/chats.tsx
  src/components/domain/live/livebids.tsx
  src/components/domain/live/livechatting.tsx
  src/components/domain/live/livedetailscroll.tsx
  src/components/domain/live/livevideo.tsx
  src/components/ui/aspect-ratio.tsx
  src/components/ui/menubar.tsx
  src/pages/auctionlist/[auctionid]/live/index.tsx
  tailwind.config.ts
Labels: :bulb: Feature

#23 공통 Footer 와이어프레임 적용
  src/components/common/AuctionDetail.tsx
  src/components/common/AuctionDetailContents.tsx
  src/components/common/Footer.tsx
  src/components/common/Layout.tsx
  src/pages/auctionlist/[auctionid]/live/index.tsx
Labels: :bulb: Feature

#30 Feat/pjw980921/25
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  public/svgs/.gitkeep
  public/svgs/eye_off.svg
  public/svgs/eye_on.svg
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/domain/myPage/Tabs/MyPageTabs.tsx
  src/components/ui/AuthInput.tsx
  src/components/ui/ErrorMessage.tsx
  src/components/ui/separator.tsx
  src/components/ui/tabs.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/services/api.ts
  src/services/axios.ts
  src/types/types.ts
  src/types/validation.ts
Labels: :bulb: Feature, :gear: Setting

#33 axios/api 파일 수정
  src/services/api.ts
Labels: :bug: Bug Fix

#35 Type 및 Mockup Data 수정
  src/mocks/Art.ts
  src/mocks/Auction.ts
  src/mocks/Member.ts
  src/mocks/PurchaseHistory.ts
  src/mocks/SalesHistory.ts
  src/services/api.ts
  src/types/types.ts
Labels: :bulb: Feature, :hammer_and_wrench: Refactor

#38 Feat/hyun522/36 header 공동컴포넌트 / 로그인 로그아웃 구현
  package-lock.json
  package.json
  src/components/common/Header.tsx
  src/components/ui/dropdown-menu.tsx
Labels: :bulb: Feature

#40 day.js 파일 생성
  src/lib/Date.ts
Labels: :bulb: Feature

#43 인풋/에러메세지 커스텀 (merge X)
  .vscode/settings.json
  package-lock.json
  package.json
  public/svgs/email-icon.svg
  public/svgs/eye_off.svg
  public/svgs/eye_on.svg
  public/svgs/kakao-icon.svg
  public/svgs/pwd-icon.svg
  src/components/common/AuctionDetail.tsx
  src/components/domain/live/chats.tsx
  src/components/domain/live/livebids.tsx
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/svgs/Email.tsx
  src/components/svgs/Pwd.tsx
  src/components/ui/AuthInput.tsx
  src/components/ui/ErrorMessage.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/pages/mypage/index.tsx
  src/styles/globals.css
  src/types/validation.ts
  tailwind.config.ts
Labels: :art: Style, :bulb: Feature, :gear: Setting, :hammer_and_wrench: Refactor

#46 Feat/hyun522/39
  package-lock.json
  package.json
  src/components/common/Header.tsx
  src/components/ui/hover-card.tsx
Labels: 🖼️Design

#49 경매 등록 페이지 1차 와이어프레임 기반 작성
  package-lock.json
  package.json
  src/components/common/Layout.tsx
  src/components/domain/live/date-time-picker-demo.tsx
  src/components/domain/live/time-picker-demo.tsx
  src/components/domain/live/time-picker-input.tsx
  src/components/domain/live/time-picker-utils.tsx
  src/components/ui/calendar.tsx
  src/components/ui/menubar.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/pages/auctionadd/index.tsx
  src/types/types.ts
  src/types/validation.ts
Labels: :bulb: Feature

#51 authInput 컴포넌트 수정
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/svgs/EmailIcon.tsx
  src/components/svgs/PwdIcon.tsx
  src/components/ui/AuthInput.tsx
Labels: :bug: Bug Fix

#56 Edit 컴포넌트 수정
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/ui/AuthInput.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/textarea.tsx
  src/pages/mypage/index.tsx
  src/styles/globals.css
  src/types/newPwdValidation.ts
  src/types/validation.ts
Labels: :art: Style, :bug: Bug Fix, :bulb: Feature

#61 refactor: Layout 적용 예외 path 추가
  src/components/common/Layout.tsx
  src/pages/_app.tsx
Labels: :hammer_and_wrench: Refactor

#62 myPageTabs 컴포넌트 UI 구현
  public/svgs/yumu-logo.svg
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/domain/myPage/Tabs/MyPageTabs.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/components/ui/AuthInput.tsx
  src/components/ui/ErrorMessage.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/mocks/PurchaseHistory.ts
  src/mocks/SalesHistory.ts
  src/mocks/WishList.ts
  src/pages/mypage/detail/index.tsx
  src/pages/mypage/index.tsx
  src/types/types.ts
  tailwind.config.ts
Labels: :art: Style, :bulb: Feature, :hammer_and_wrench: Refactor

#69 개발 완료 된 경매 등록 페이지 api 검토 및 적용
  package-lock.json
  package.json
  src/pages/registration/index.tsx
  src/services/api.ts
  src/types/types.ts
  src/types/validation.ts
Labels: :bulb: Feature

#70 api.ts 수정
  src/components/common/AuctionCard.tsx
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/contexts/AuthProvider.tsx
  src/mocks/Art.ts
  src/mocks/Auction.ts
  src/mocks/Member.ts
  src/mocks/PurchaseHistory.ts
  src/mocks/SalesHistory.ts
  src/mocks/WishList.ts
  src/pages/registration/index.tsx
  src/services/api.ts
  src/types/types.ts
Labels: :hammer_and_wrench: Refactor

#72 validator 폴더 생성
  pull_request_template.md
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/pages/registration/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/validator/auctionForm.ts
  src/types/validator/myPageForm.ts
  src/types/validator/signForm.ts
Labels: :gear: Setting

#75 Live/Streaming 페이지에 Socket.io 적용 ( 실시간 채팅만) (미완)
  src/pages/api/socket/chat.ts
  src/pages/api/socket/io.ts
  src/pages/chatting/index.tsx
  src/types/next.ts
Labels: :bulb: Feature

#76 Feat/hyun522/48 main 페이지 - 베너 구현
  package-lock.json
  package.json
  public/svgs/banner-1.svg
  public/svgs/navButtonLeft-off.svg
  public/svgs/navButtonRight-on.svg
  public/svgs/search-icon.svg
  public/svgs/yumu-logo.svg
  src/components/common/Header.tsx
  src/components/common/SearchForm.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/pages/landing/index.tsx
Labels: :bulb: Feature, 🖼️Design

#79 tailwind.config에 텍스트 스타일링 일부 추가 및 streaming 페이지의 유의사항 div UI 적용
  src/pages/auction/[auctionid]/streaming/index.tsx
  tailwind.config.ts
Labels: :art: Style

#84 라이브 경매 페이지 UI 적용 - 채팅박스
  src/components/common/AuctionDetail.tsx
  src/components/domain/live/bids.tsx
  src/components/domain/live/chats.tsx
  src/components/domain/live/livechatting.tsx
  src/components/domain/live/livevideo.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/pages/auction/[auctionid]/streaming/index.tsx
  tailwind.config.ts
Labels: 🖼️Design

#88 라이브 경매 페이지 UI 적용 -> 현재 응찰 정보 박스
  src/components/domain/live/BidHistories.tsx
  src/components/domain/live/livebids.tsx
  src/components/domain/live/livechatting.tsx
  src/pages/auction/[auctionid]/live/index.tsx
  src/pages/auction/[auctionid]/streaming/index.tsx
  tailwind.config.ts
Labels: 🖼️Design

#92 라이브 경매 페이지 UI 적용 - 상세
  src/components/common/AuctionDetail.tsx
  src/pages/auction/[auctionid]/live/index.tsx
Labels: :bulb: Feature, 🖼️Design

#94 검색 페이지 기능 테스트 구현
  next.config.mjs
  package-lock.json
  package.json
  src/components/common/AuctionCard.tsx
  src/components/common/EmptyView.tsx
  src/components/common/Pagination.tsx
  src/components/common/SearchForm.tsx
  src/components/domain/search/AuctionList.tsx
  src/mocks/testArts.json
  src/pages/_app.tsx
  src/pages/search/index.tsx
Labels: :bug: Bug Fix, :bulb: Feature

#95 axios 수정
  next.config.mjs
  package-lock.json
  package.json
  src/components/domain/live/BidHistories.tsx
  src/components/domain/live/livechatting.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/hover-card.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
  src/pages/mypage/index.tsx
  src/services/api.ts
  src/services/axios.ts
  src/styles/globals.css
  src/types/types.ts
  tailwind.config.ts
Labels: :gear: Setting

#97 라이브 경매 UI 적용 - 스크롤 버튼
  src/components/common/ScrollButton.tsx
  src/components/common/ScrollButtons.tsx
  src/pages/auction/[auctionid]/live/index.tsx
  src/pages/auction/[auctionid]/streaming/index.tsx
Labels: :bulb: Feature

#98 라이브 경매 페이지에 폰트 적용
  src/components/common/AuctionDetail.tsx
  src/components/common/ScrollButton.tsx
  src/components/domain/live/BidHistories.tsx
  src/components/domain/live/livechatting.tsx
  src/pages/auction/[auctionid]/streaming/index.tsx
  tailwind.config.ts
Labels: 🖼️Design

#102 회원가입 유효성오류, 로그인 페이지 오류 수정
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/types.ts
  src/types/validator/signForm.ts
Labels: :bug: Bug Fix

#104 경매 상세 페이지 마크업 및 UI 디자인 구현
  public/images/.gitkeep
  public/images/heart_off.png
  public/images/heart_on.png
  src/components/common/AuctionCard.tsx
  src/components/common/InfoBox.tsx
  src/components/common/Layout.tsx
  src/components/common/LikeButton.tsx
  src/pages/auction/[auctionid]/detail/index.tsx
  src/pages/search/index.tsx
Labels: :bulb: Feature, :hammer_and_wrench: Refactor, 🖼️Design

#106 accessToken/refreshToken 적용
  next.config.mjs
  src/services/api.ts
  src/services/axios.ts
  src/types/types.ts
Labels: :gear: Setting

#109 Pagination 컴포넌트 리팩토링
  src/components/common/Pagination.tsx
  src/pages/search/index.tsx
Labels: :hammer_and_wrench: Refactor

#111 axios/api 파일 및 package.json 수정
  package-lock.json
  package.json
  src/services/api.ts
  src/services/axios.ts
Labels: :gear: Setting

#119 카카오로그인 및 로그인유효성검사 에러수정
  package-lock.json
  package.json
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/services/api.ts
  src/types/validator/signForm.ts
Labels: :bug: Bug Fix

#133 Feat/hyun522/126 현재라이브경매 디자인 추가 기능 수정 및 인기경매 API 수정
  public/svgs/m1-microphone.svg
  public/svgs/main1-moreArrow.svg
  src/components/common/Header.tsx
  src/components/ui/button.tsx
  src/pages/landing/index.tsx
Labels: :bulb: Feature, 🖼️Design

#134 마이페이지 내역 화면 디자인 적용
  .vscode/settings.json
  public/images/artImage.png
  public/svgs/my-page-arrow-icon.svg
  public/svgs/my-page-buy-black-icon.svg
  public/svgs/my-page-buy-gray-icon.svg
  public/svgs/my-page-modal-close-icon.svg
  public/svgs/my-page-sales-black-icon.svg
  public/svgs/my-page-sales-gray-icon.svg
  public/svgs/my-page-wish-black-icon.svg
  public/svgs/my-page-wish-gray-icon.svg
  public/svgs/profile-image.svg
  src/components/domain/myPage/Tabs/BuyHistory.tsx
  src/components/domain/myPage/Tabs/MyPageTabs.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/domain/myPage/Tabs/WishList.tsx
  src/components/ui/alert-dialog.tsx
  src/components/ui/button.tsx
  src/components/ui/tabs.tsx
  src/lib/Date.ts
  src/mocks/SalesHistory.ts
  src/pages/mypage/index.tsx
  src/styles/globals.css
  src/types/types.ts
  tailwind.config.ts
Labels: :art: Style, :gear: Setting

#136 chore: 브랜치정리
  src/pages/signin/index.tsx
  src/types/validator/signForm.ts
Labels: :bug: Bug Fix, 🔩 chore

#138 검색 페이지 디자인 시안 적용 및 기능 수정
  public/svgs/arrow_first.svg
  public/svgs/arrow_last.svg
  public/svgs/arrow_next.svg
  public/svgs/arrow_prev.svg
  public/svgs/chevron_down.svg
  src/components/common/Pagination.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SortSelect.tsx
  src/pages/search/index.tsx
Labels: :bulb: Feature, 🖼️Design

#144 경매 등록 UI 적용
  package-lock.json
  package.json
  src/components/ui/input.tsx
  src/pages/api/socket/chat/[roomName].ts
  src/pages/api/socket/chat/index.ts
  src/pages/chatting/[roomId].tsx
  src/pages/chatting/index.tsx
  src/pages/registration/index.tsx
  src/services/api.ts
  src/services/axios.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🖼️Design

#147 마이페이지 정보 수정 디자인 적용
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/domain/myPage/Tabs/Edit/IntroEditForm.tsx
  src/components/domain/myPage/Tabs/Edit/NewPasswordModalForm.tsx
  src/components/domain/myPage/Tabs/Edit/NickNameEditForm.tsx
  src/components/domain/myPage/Tabs/Edit/UserDeleteModal.tsx
  src/components/domain/myPage/Tabs/SalesHistory.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/my-page-textarea.tsx
  src/pages/mypage/index.tsx
  src/styles/globals.css
  src/types/validator/myPageForm.ts
  tailwind.config.ts
Labels: :art: Style, :gear: Setting, :hammer_and_wrench: Refactor

#150 Feat/hyun522/132
  public/svgs/openLive.svg
  src/components/common/BestAuction.tsx
  src/components/common/ExhibitionCarousel.tsx
  src/components/domain/landing/LandingBanner.tsx
  src/components/domain/landing/LandingLivePopular.tsx
  src/components/ui/button.tsx
  src/components/ui/mainCarousel.tsx
  src/pages/landing/index.tsx
Labels: :bulb: Feature, 🖼️Design, 🔩 chore

#152 design: 잠실체 적용된 폰트 전체 수정
  src/components/common/AuctionDetail.tsx
  src/components/common/BestAuction.tsx
  src/components/domain/landing/LandingLivePopular.tsx
  src/pages/auction/[auctionid]/detail/index.tsx
  src/pages/auction/[auctionid]/live/index.tsx
  src/pages/auction/[auctionid]/streaming/index.tsx
  src/pages/landing/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🖼️Design

#154 카카오 로그인 토큰가져오기 시도중입니다.
  package-lock.json
  package.json
  src/pages/callback/index.tsx
  src/pages/signin/callback/index.tsx
  src/pages/signin/index.tsx
  src/services/api.ts
Labels: :bulb: Feature, 🔩 chore

#153 feat : header 공동 컴포넌트 작업
  src/components/common/Header.tsx
Labels: :bulb: Feature

#155 경매 등록 페이지 api 적용
  src/pages/api/socket/chat.ts
  src/pages/api/socket/chat/[roomName].ts
  src/pages/api/socket/chat/index.ts
  src/pages/api/socket/io.ts
  src/pages/registration/index.tsx
  src/services/api.ts
  src/services/axios.ts
  src/types/types.ts
  src/types/validator/auctionForm.ts
Labels: :bulb: Feature

#157 경매 등록 페이지 UI 재적용
  src/pages/registration/index.tsx
  tailwind.config.ts
Labels: 🖼️Design

#158 마이페이지 정보 수정 기능 구현
  src/components/common/Header.tsx
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/domain/myPage/Tabs/Edit/IntroEditForm.tsx
  src/components/domain/myPage/Tabs/Edit/NickNameEditForm.tsx
  src/contexts/AuthProvider.tsx
  src/mocks/Member.ts
  src/pages/detail/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signup/index.tsx
  src/services/api.ts
  src/services/axios.ts
  src/types/types.ts
  tailwind.config.ts
Labels: :bug: Bug Fix, :bulb: Feature, :gear: Setting

#160 마이페이지 정보 수정 기능 구현 마무리 작업
  src/components/domain/myPage/Tabs/Edit/Edit.tsx
  src/components/domain/myPage/Tabs/Edit/NewPasswordModalForm.tsx
  src/components/domain/myPage/Tabs/Edit/UserDeleteModal.tsx
  src/components/ui/AuthInput.tsx
  src/pages/callback/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/services/api.ts
  src/types/types.ts
  src/types/validator/myPageForm.ts
  src/types/validator/signForm.ts
Labels: :bug: Bug Fix, :bulb: Feature, :gear: Setting, :hammer_and_wrench: Refactor

#168 경매 등록 성공 시에 경매 검색 페이지로 이동하는 기능 추가
  src/pages/registration/index.tsx
  src/services/api.ts
Labels: :bulb: Feature

#169 live 페이지 최신 UI 적용
  src/components/common/AuctionDetail.tsx
  src/components/common/InfoBox.tsx
  src/components/domain/live/BiddingBox.tsx
  src/pages/auction/[auctionid]/live/index.tsx
  src/pages/auction/[auctionid]/streaming/index.tsx
  src/styles/globals.css
  src/types/types.ts
Labels: :bulb: Feature
